Remove IngestionAwareTransport
hashicorp/memberlist pull request #230
Opened 2021-02-16 18:53 UTC by dnephin

This interface is never used by memberlist. The passed in transport may implement this interface, or any other interface, but memberlist does not need to be aware of it.

2021-02-18 13:45 UTC, banks requested changes
While it might have been cleaner to never expose this, I don't think we can just remove it without breaking backwards compatibility gaurantees which is not allowed by Go modules/semantic versioning unless we release a v2.

The issue is that even if memberlist doesn't use this outside test code, downstream code might explicitly type switch on the `memberlist.IngestionAwareTransport` interface type or use it as a struct field or argument type [like we do in Consul](https://github.com/hashicorp/consul/blob/a4327305d1ca583ae459f1d0e3eeacc6805b4316/agent/consul/server.go#L254).

For any such consumer this would be a breaking change. I don't think it's important enough to warrant a v2 switch or breaking the rules of semantic versioning to undo this even if it could have been left out of the interface originally.

2021-02-18 21:13 UTC, dnephin commented
I agree with most of that argument, but I think a reasonable argument can be made that this is not in fact a breaking change.

It is no surprise that Consul imports it, because this was added for Consul. There is no logical reason for any other code to import this symbol because it is only used by Consul. Any other user would chose a different name for this interface and the methods and would have no reason to use this un-referenced interface from memberlist.

At the very least removing the shim and the embedding of this type in `NodeAwareTransport` is a safe change. We could leave the interface itself sitting there and document that it is not used, but it seems very unlikely that anyone would reference it. A [github search](https://github.com/search?p=2&q=IngestionAwareTransport&type=Code) shows at least no public code on github uses it.

2021-02-22 16:50 UTC, banks commented
Yeah, I doubt that it would be experienced as a breaking change by anyone - certainly not many if it is.

I see it as the better option to not break backwards compatibility of a public library in any way unless there is a _really_ good reason like a CVE or major bug which I don't think this qualifies as 🤷.  To me it doesn't seem important enough either way to spend lots of time on so I'd err for the safer option personally but won't loose sleep if others disagree 😄 .

Your suggestion of doing most of this but leaving a stub interface definition with a deprecation comment seems like a reasonable path forward to me that makes it a trivial merge again. What do you think?

Open to input from others too!

2021-04-08 18:22 UTC, dnephin reviewed
Sounds good, I've made those changes.

I restored the interface, but added a deprecation comment. The shim changes should be backwards compatible.

2021-04-08 18:22 UTC, dnephin commented on net_test.go
> +	}
Using a local interface here to prevent referencing the deprecated interface.

2021-04-12 16:38 UTC, banks approved these changes
LGTM thanks!

2021-04-12 16:42 UTC, merged